In [1]:
import SDEC.datos.codigos.lectura_datos_salarios as ld

In [2]:
sal,geo, centroides, codiprov,personas = ld.df_salarios()

d:\Anaconda3\envs\geo\Lib\site-packages\pyogrio\raw.py:198: RuntimeWarning: driver ESRI Shapefile does not support open option INDEX
  return ogr_read(

In [3]:
sal

               index   puestos  clae_bajo  clae_alto      w_mean codpcia  \
link  mes
6007  2014-01      0    3654.0      109.0      268.0    489287.0      06
      2014-02      1  488087.0   174360.0    28408.0    428803.0      06
      2014-03      2   43940.0     4250.0    18043.0    454412.0      06
      2014-04      3   21120.0    11580.0      590.0    438001.0      06
      2014-05      4   24352.0     8157.0     3186.0    460928.0      06
...              ...       ...        ...        ...         ...     ...
94014 2023-07  59971   14994.0     4703.0     1912.0  36212507.0      94
      2023-08  59972   27528.0     1357.0     3495.0  40434111.0      94
      2023-09  59973   12275.0     1414.0     7027.0  44950817.0      94
      2023-10  59974   11424.0     1876.0     4879.0  47322353.0      94
      2023-11  59975   37608.0     4197.0    10991.0  55100920.0      94

                  departamen         provincia  mujeres  varones  personas  \
link  mes
6007  2014-01  Adolfo Alsina      Buenos Aires     8667     8405     17072
      2014-02  Adolfo Alsina      Buenos Aires     8667     8405     17072
      2014-03  Adolfo Alsina      Buenos Aires     8667     8405     17072
      2014-04  Adolfo Alsina      Buenos Aires     8667     8405     17072
      2014-05  Adolfo Alsina      Buenos Aires     8667     8405     17072
...                      ...               ...      ...      ...       ...
94014 2023-07        Ushuaia  Tierra del Fuego    27826    29130     56956
      2023-08        Ushuaia  Tierra del Fuego    27826    29130     56956
      2023-09        Ushuaia  Tierra del Fuego    27826    29130     56956
      2023-10        Ushuaia  Tierra del Fuego    27826    29130     56956
      2023-11        Ushuaia  Tierra del Fuego    27826    29130     56956

               hogares  viv_part  viv_part_h  \
link  mes
6007  2014-01     6237      7932        6097
      2014-02     6237      7932        6097
      2014-03     6237      7932        6097
      2014-04     6237      7932        6097
      2014-05     6237      7932        6097
...                ...       ...         ...
94014 2023-07    17538     20054       16891
      2023-08    17538     20054       16891
      2023-09    17538     20054       16891
      2023-10    17538     20054       16891
      2023-11    17538     20054       16891

                                                        geometry
link  mes
6007  2014-01  POLYGON ((3742770.651 5945103.437, 3743040.9 5...
      2014-02  POLYGON ((3742770.651 5945103.437, 3743040.9 5...
      2014-03  POLYGON ((3742770.651 5945103.437, 3743040.9 5...
      2014-04  POLYGON ((3742770.651 5945103.437, 3743040.9 5...
      2014-05  POLYGON ((3742770.651 5945103.437, 3743040.9 5...
...                                                          ...
94014 2023-07  MULTIPOLYGON (((3411670.691 3913786.98, 341161...
      2023-08  MULTIPOLYGON (((3411670.691 3913786.98, 341161...
      2023-09  MULTIPOLYGON (((3411670.691 3913786.98, 341161...
      2023-10  MULTIPOLYGON (((3411670.691 3913786.98, 341161...
      2023-11  MULTIPOLYGON (((3411670.691 3913786.98, 341161...

[59976 rows x 15 columns]

In [56]:
sal = ld.pd.read_csv(ld.dir_datos+'sal.csv')
sal.drop(sal.columns[0], axis = 1, inplace=True)
sal = sal.set_index([sal.columns[0],sal.columns[1],sal.columns[2]])
sal

                                            id_provincia_indec    w_mean  \
codigo_departamento_indec clae2 fecha
2000.0                    1     2014-01-01                 2.0   13067.0
                                2014-02-01                 2.0   13119.0
                                2014-03-01                 2.0   13392.0
                                2014-04-01                 2.0   15039.0
                                2014-05-01                 2.0   13941.0
...                                                        ...       ...
94014.0                   999   2023-07-01                94.0  374436.0
                                2023-08-01                94.0  479442.0
                                2023-09-01                94.0  480174.0
                                2023-10-01                94.0  481935.0
                                2023-11-01                94.0  510385.0

                                            puestos         masa      masa_cer
codigo_departamento_indec clae2 fecha
2000.0                    1     2014-01-01   5477.0   71567959.0  2.006560e+07
                                2014-02-01    972.0   12751668.0  3.465410e+06
                                2014-03-01    152.0    2035584.0  5.346950e+05
                                2014-04-01    119.0    1789641.0  4.574630e+05
                                2014-05-01      0.0          0.0  0.000000e+00
...                                             ...          ...           ...
94014.0                   999   2023-07-01      0.0          0.0  0.000000e+00
                                2023-08-01     28.0   13424376.0  1.091528e+05
                                2023-09-01      3.0    1440522.0  1.072603e+04
                                2023-10-01     39.0   18795465.0  1.241051e+05
                                2023-11-01    202.0  103097770.0  6.173721e+05

[4467498 rows x 5 columns]

In [41]:
sal.reset_index().dtypes

codigo_departamento_indec    float64
clae2                          int64
fecha                         object
id_provincia_indec           float64
w_mean                       float64
puestos                      float64
masa                         float64
masa_cer                     float64
clae_bajo                    float64
dtype: object

In [19]:
clae = sal.groupby(level = [1,2]).sum()
clae['prom_clae'] = clae['masa_cer']/clae['puestos']
clae = clae.groupby(level = 0).mean()
clae

,id_provincia_indec,w_mean,puestos,masa,masa_cer,prom_clae
clae2,,,,,,
1,18458.201681,2.477665e+07,150074.697479,7.367533e+09,2.819392e+08,1895.858854
2,11655.697479,1.053981e+07,97396.848739,3.348972e+09,1.163100e+08,1240.920729
3,8436.957983,3.053031e+07,83006.100840,9.042244e+09,3.715636e+08,4516.512412
5,3353.831933,3.530673e+06,21018.168067,7.330614e+08,3.284547e+07,1599.762218
6,9473.865546,6.234477e+07,96006.117647,1.841138e+10,7.336130e+08,7745.205730
...,...,...,...,...,...,...
93,14268.672269,1.598345e+07,133996.773109,5.168188e+09,2.072802e+08,1553.745107
94,17559.747899,3.012570e+07,152481.882353,9.734424e+09,3.677036e+08,2408.834883
95,7809.831933,7.239086e+06,76275.512605,2.353575e+09,9.414436e+07,1250.043374
96,16216.537815,1.835178e+07,136360.865546,5.575053e+09,2.178620e+08,1610.494180
999,6749.109244,8.952037e+06,62149.067227,2.539248e+09,1.044905e+08,1722.187687

In [23]:
clae_bajo = clae.sort_values('prom_clae').head(20)
clae_alto = clae.sort_values('prom_clae').tail(20)

In [24]:
clae_bajo

,id_provincia_indec,w_mean,puestos,masa,masa_cer,prom_clae
clae2,,,,,,
90,7488.722689,4.931080e+06,69829.840336,1.305947e+09,5.796789e+07,857.330516
75,9861.697479,8.574969e+06,103281.571429,2.494956e+09,1.040031e+08,1029.091184
91,6649.579832,6.514110e+06,74365.462185,1.761620e+09,8.358227e+07,1137.243194
88,8087.630252,7.031830e+06,69278.302521,2.105964e+09,8.543076e+07,1181.545077
81,17489.899160,1.429749e+07,151062.882353,4.822742e+09,1.763002e+08,1181.849891
2,11655.697479,1.053981e+07,97396.848739,3.348972e+09,1.163100e+08,1240.920729
95,7809.831933,7.239086e+06,76275.512605,2.353575e+09,9.414436e+07,1250.043374
78,11344.067227,9.784869e+06,101557.319328,3.951429e+09,1.474905e+08,1387.840388
87,12134.739496,1.310470e+07,103697.815126,3.761447e+09,1.440884e+08,1389.899740
16,13381.176471,1.356854e+07,120924.436975,4.151673e+09,1.732881e+08,1423.239829
31,11632.789916,1.277132e+07,105427.815126,4.417878e+09,1.550548e+08,1426.543809
56,17701.882353,1.812044e+07,158731.621849,6.394582e+09,2.282455e+08,1430.246961
59,7451.932773,8.630529e+06,75918.226891,2.992823e+09,1.167818e+08,1514.354443
74,8780.453782,1.271770e+07,83030.453782,3.669004e+09,1.285496e+08,1524.122327
14,12892.134454,1.415660e+07,119817.092437,4.773704e+09,1.838818e+08,1526.080722
93,14268.672269,1.598345e+07,133996.773109,5.168188e+09,2.072802e+08,1553.745107
41,18067.176471,2.045343e+07,150065.294118,6.559986e+09,2.329681e+08,1554.017830
5,3353.831933,3.530673e+06,21018.168067,7.330614e+08,3.284547e+07,1599.762218
79,12080.924370,1.380850e+07,110355.260504,4.697734e+09,1.783358e+08,1600.144725
96,16216.537815,1.835178e+07,136360.865546,5.575053e+09,2.178620e+08,1610.494180

In [25]:
clae_alto

,id_provincia_indec,w_mean,puestos,masa,masa_cer,prom_clae
clae2,,,,,,
53,17133.848739,3.314338e+07,155538.302521,1.070270e+10,4.891377e+08,3177.630028
60,15388.857143,3.222538e+07,137288.588235,1.077359e+10,4.365353e+08,3183.621476
65,15990.924370,3.560196e+07,136212.680672,1.152982e+10,4.542647e+08,3285.365125
49,17950.487395,4.187795e+07,154378.226891,1.311412e+10,5.111508e+08,3301.959601
12,5542.840336,1.244505e+07,47606.134454,4.281153e+09,1.691380e+08,3411.730786
62,13750.033613,4.186656e+07,123203.764706,1.191103e+10,4.277964e+08,3439.836517
72,14946.386555,3.933777e+07,137900.537815,1.201693e+10,4.809737e+08,3469.622998
36,14944.924370,3.729032e+07,127041.647059,1.213816e+10,4.622890e+08,3658.885230
61,14319.512605,4.053470e+07,126054.403361,1.235171e+10,4.734099e+08,3764.936132
19,5591.445378,1.593853e+07,58930.336134,5.709346e+09,2.322959e+08,3852.336328
20,15519.042017,4.508796e+07,128542.336134,1.295932e+10,5.055455e+08,3899.837754
51,7822.823529,2.895776e+07,85747.806723,8.660023e+09,3.760767e+08,4385.798649
3,8436.957983,3.053031e+07,83006.100840,9.042244e+09,3.715636e+08,4516.512412
21,10319.478992,3.929755e+07,103589.537815,1.396712e+10,5.130880e+08,4922.200776
50,6322.521008,2.870859e+07,66916.865546,8.943489e+09,3.479340e+08,5273.930328
9,13580.436975,5.648044e+07,111255.294118,1.668910e+10,6.632583e+08,5958.270657
7,10851.142857,4.537040e+07,82287.184874,1.499305e+10,5.247328e+08,6185.037669
35,17400.504202,7.613579e+07,155559.445378,2.602590e+10,9.648525e+08,6218.421751
64,16751.210084,8.925918e+07,143755.319328,2.795570e+10,1.011231e+09,7056.149918
6,9473.865546,6.234477e+07,96006.117647,1.841138e+10,7.336130e+08,7745.205730

In [26]:
clae_bajo.index

Index([90, 75, 91, 88, 81, 2, 95, 78, 87, 16, 31, 56, 59, 74, 14, 93, 41, 5,
       79, 96],
      dtype='int64', name='clae2')

In [50]:
l = []
for i in sal.reset_index().clae2:
    if i in list(clae_bajo.index):
        l.append(1)
    else:
        l.append(0)


sal['clae_bajo'] = ld.np.array(l) * sal['puestos']
sal.sum()

id_provincia_indec    1.326246e+08
w_mean                2.497983e+11
puestos               1.180580e+09
masa                  7.942496e+13
masa_cer              3.037753e+12
clae_bajo             2.454246e+08
dtype: float64

In [51]:
l = []
for i in sal.reset_index().clae2:
    if i in list(clae_alto.index):
        l.append(1)
    else:
        l.append(0)


sal['clae_alto'] = ld.np.array(l) * sal['puestos']
sal.sum()

id_provincia_indec    1.326246e+08
w_mean                2.497983e+11
puestos               1.180580e+09
masa                  7.942496e+13
masa_cer              3.037753e+12
clae_bajo             2.454246e+08
clae_alto             2.690377e+08
dtype: float64

In [53]:
sal.groupby(level = [0,2]).sum()

                                      id_provincia_indec      w_mean  \
codigo_departamento_indec fecha
2000.0                    2014-01-01               172.0   1458475.0
                          2014-02-01               172.0   1383092.0
                          2014-03-01               172.0   1555653.0
                          2014-04-01               172.0   1466666.0
                          2014-05-01               172.0   1445189.0
...                                                  ...         ...
94014.0                   2023-07-01              7802.0  36212507.0
                          2023-08-01              7802.0  40434111.0
                          2023-09-01              7802.0  44950817.0
                          2023-10-01              7802.0  47322353.0
                          2023-11-01              7708.0  55100920.0

                                        puestos          masa      masa_cer  \
codigo_departamento_indec fecha
2000.0                    2014-01-01  1146412.0  1.559151e+10  4.371411e+09
                          2014-02-01    54030.0  6.063422e+08  1.647803e+08
                          2014-03-01    24909.0  1.027480e+09  2.698924e+08
                          2014-04-01    29973.0  3.806337e+08  9.729652e+07
                          2014-05-01     8846.0  1.120725e+08  2.810172e+07
...                                         ...           ...           ...
94014.0                   2023-07-01    14994.0  6.419700e+09  5.541087e+07
                          2023-08-01    27528.0  1.179907e+10  9.593757e+07
                          2023-09-01    12275.0  7.559829e+09  5.628997e+07
                          2023-10-01    11424.0  6.464938e+09  4.268751e+07
                          2023-11-01    37608.0  2.698088e+10  1.615675e+08

                                      clae_bajo  clae_alto
codigo_departamento_indec fecha
2000.0                    2014-01-01   121027.0   194398.0
                          2014-02-01    32900.0     9429.0
                          2014-03-01     2263.0    11768.0
                          2014-04-01     6434.0     2197.0
                          2014-05-01     1885.0      446.0
...                                         ...        ...
94014.0                   2023-07-01     4703.0     1912.0
                          2023-08-01     1357.0     3495.0
                          2023-09-01     1414.0     7027.0
                          2023-10-01     1876.0     4879.0
                          2023-11-01     4197.0    10991.0

[60095 rows x 7 columns]

In [54]:
sal

                                            id_provincia_indec    w_mean  \
codigo_departamento_indec clae2 fecha
2000.0                    1     2014-01-01                 2.0   13067.0
                                2014-02-01                 2.0   13119.0
                                2014-03-01                 2.0   13392.0
                                2014-04-01                 2.0   15039.0
                                2014-05-01                 2.0   13941.0
...                                                        ...       ...
94014.0                   999   2023-07-01                94.0  374436.0
                                2023-08-01                94.0  479442.0
                                2023-09-01                94.0  480174.0
                                2023-10-01                94.0  481935.0
                                2023-11-01                94.0  510385.0

                                            puestos         masa  \
codigo_departamento_indec clae2 fecha
2000.0                    1     2014-01-01   5477.0   71567959.0
                                2014-02-01    972.0   12751668.0
                                2014-03-01    152.0    2035584.0
                                2014-04-01    119.0    1789641.0
                                2014-05-01      0.0          0.0
...                                             ...          ...
94014.0                   999   2023-07-01      0.0          0.0
                                2023-08-01     28.0   13424376.0
                                2023-09-01      3.0    1440522.0
                                2023-10-01     39.0   18795465.0
                                2023-11-01    202.0  103097770.0

                                                masa_cer  clae_bajo  clae_alto
codigo_departamento_indec clae2 fecha
2000.0                    1     2014-01-01  2.006560e+07        0.0        0.0
                                2014-02-01  3.465410e+06        0.0        0.0
                                2014-03-01  5.346950e+05        0.0        0.0
                                2014-04-01  4.574630e+05        0.0        0.0
                                2014-05-01  0.000000e+00        0.0        0.0
...                                                  ...        ...        ...
94014.0                   999   2023-07-01  0.000000e+00        0.0        0.0
                                2023-08-01  1.091528e+05        0.0        0.0
                                2023-09-01  1.072603e+04        0.0        0.0
                                2023-10-01  1.241051e+05        0.0        0.0
                                2023-11-01  6.173721e+05        0.0        0.0

[4467498 rows x 7 columns]